name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy using Docker Compose
      run: |
        sudo docker-compose pull
        sudo docker-compose up -d
